### ISSUE TITLE
Gitlab Variables environment_scope not honoured

### ISSUE THREAD

**Issue by AlexEndris** [xanzy/go-gitlab#1972]
I'm facing the issue that ExternalSecrets doesn't seem to correctly filter the variables using Gitlab Variables. The SecretStore is capable of retrieving a secret of environment "b" even though it's being restricted to "a".
Let's say I have the secrets "TEST_SECRET_A" (environment "a") and "TEST_SECRET_B" (environment "b"), neither secret exists in any other environment. 

Using this secretstore:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: a-secrets
  namespace: default
spec:
  provider:
    gitlab:
      auth:
        SecretRef:
          accessToken:
            name: xxx
            key: xxx
      projectID: "xxx"
      inheritFromGroups: false
      environment: a
```
Adding an ExternalSecret resource like this, actually retrieves the secret:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-external-secret-b
  namespace: default
spec:
  refreshInterval: 1m

  secretStoreRef:
    kind: SecretStore
    name: a-secrets

  target:
    name: b-secret 
    creationPolicy: Owner

  data:
    - secretKey: secretKey
      remoteRef: 
        key: TEST_SECRET_B
```

Trying the same using the gitlab API with the filter for the environment_scope of "a" correctly returns "404 Variable Not Found". 

Am I doing something wrong or is this indeed a bug?
